### PR TITLE
Add null check

### PR DESCRIPTION
**Pull request by jonsadka**
cc @enjalot @nateps @ishbu 

Fixes: 
Cannot read property 'status' of undefined
var/lever/hire2/node_modules/l-upload/index in nextWaiting
https://app.getsentry.com/hireleverco/hire-production/group/27133493/

### CODE REVIEW

**Comment by ishbu** [comment]
you need file?.status

**Comment by jonsadka** [comment]
@ishbu Done :)

**Comment by ishbu** [comment]
LGTM

**Comment by kevinliang** [comment]
hi guys :)

**Comment by kevinliang** [comment]
LGTM

**Comment by jonsadka** [comment]
KEV!!!!

**Pull request merged**
